In [1]:
%pip install pandas

Requirement already satisfied: pandas in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2.4.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\student\appdata\roaming\python\python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\student\appdata\local\programs\python\python312\lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in c:\users\student\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 24.0 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import pandas as pd

# Load dataset
df = pd.read_csv("../data/raw/overview.csv")

# Quick look
df.head()

,ID,Country,APT-group,Family,Status,MD5,SHA1,SHA256,Source
0,1,China,APT 1,NaN,V,001dd76872d80801692ff942308c64e6,7f4d6745b9053583b55b87bb16a88840e56e5621,b6bc96ffcbdbf22f908a02b8fe2a392c8e5b8420a12093...,https://www.fireeye.com/content/dam/fireeye-ww...
1,2,China,APT 1,NaN,V,002325a0a67fded0381b5648d7fe9b8e,ee4c025731e791fb358f5f03e9d95fc86ee0a723,3bff207897f6d8cd8f8e178a565d5efdd7d65c6bc27063...,https://www.fireeye.com/content/dam/fireeye-ww...
2,3,China,APT 1,NaN,V,00dbb9e1c09dbdafb360f3163ba5a3de,8f096561d4021978f781cc3978a55d0f621fc837,df649cef1505653a2fc4361f1e2e34f7148b60c00e1cf6...,https://www.fireeye.com/content/dam/fireeye-ww...
3,4,China,APT 1,NaN,X,00f24328b282b28bc39960d55603e380,NaN,NaN,https://www.fireeye.com/content/dam/fireeye-ww...
4,5,China,APT 1,NaN,X,0115338e11f85d7a2226933712acaae8,NaN,NaN,https://www.fireeye.com/content/dam/fireeye-ww...

In [3]:
df.shape

(4449, 9)

In [4]:

df.columns

Index(['ID', 'Country', 'APT-group', 'Family', 'Status', 'MD5', 'SHA1',
       'SHA256', 'Source'],
      dtype='str')

In [5]:
df.isnull().sum()

ID              0
Country         0
APT-group       0
Family       1818
Status          0
MD5           125
SHA1          855
SHA256        730
Source          0
dtype: int64

In [6]:
df['APT-group'].nunique()

12

In [7]:
df['APT-group'].value_counts()

APT-group
Gorgon Group      1085
APT 1             1007
Winnti             406
Equation Group     395
APT 10             300
Dark Hotel         298
APT 29             281
APT 28             230
APT 30             164
Energetic Bear     132
APT 21             118
APT 19              33
Name: count, dtype: int64

In [8]:
df.sample(10)

,ID,Country,APT-group,Family,Status,MD5,SHA1,SHA256,Source
2440,2441,Russia,Energetic Bear,Havex,V,094e63b3e14ca69f261c3695130f7d4e,ffdbf9aae672375cdb0aa6df2bab22549915d22f,e38aa99eff1f9fedd99cf541c3255e99f3276839a883ca...,https://media.kasperskycontenthub.com/wp-conte...
140,141,China,APT 1,NaN,X,22d9466d6aab8410bea006b5d3df8bd0,NaN,NaN,https://www.fireeye.com/content/dam/fireeye-ww...
702,703,China,APT 1,NaN,V,b1912db011633d98bc40ac568a4167a7,4383afa57dcfa49af4abf0bf31b20d707536e4b5,873c459c3c3aa7f0e9a488f69c4391669cbf24c6db7f5f...,https://www.fireeye.com/content/dam/fireeye-ww...
1621,1622,Russia,APT 28,NaN,V,12a9fff59de1663dec1b45ea2ede22f5,d00ac5498d0735d5ae0dea42a1f477cf8b8b0826,68065abd6482405614d245537600ea60857c6ec9febac4...,https://contagiodump.blogspot.com/2017/02/russ...
60,61,China,APT 1,NaN,X,0df42947e167cd006b176d305c08d57e,NaN,NaN,https://www.fireeye.com/content/dam/fireeye-ww...
450,451,China,APT 1,NaN,X,6f6abd53e10567d1534514fc36fca2e9,NaN,NaN,https://www.fireeye.com/content/dam/fireeye-ww...
365,366,China,APT 1,NaN,V,5bcaa2f4bc7567f6ffd5507a161e221a,060676f10c93d110af5383d68fd20c812d5eb367,98f400cceed112792e562728a4d66c7c18712684f47290...,https://www.fireeye.com/content/dam/fireeye-ww...
107,108,China,APT 1,NaN,V,1a0c7e61bcc50d57b7bcf9d9af691de5,f192ca6e6b143ecbcff10d76407832e184ea88b3,f27593fd1d391f9925230a1abc12b8f3791fc43ea980ec...,https://www.fireeye.com/content/dam/fireeye-ww...
3007,3008,Pakistan,Gorgon Group,Different RATs,V,248bbade477d88d0725d7d4ec48a5587,21294f812e870a1ae97598c66889d7e68adcea10,ccf11edb3c7aa64ebf7eaff916b0894fbe1e500a61cf3d...,https://github.com/pan-unit-42/iocs/blob/maste...
3122,3123,Pakistan,Gorgon Group,Different RATs,V,c907e2351ddd1ff0a8f64f0155c2cd66,114c4134bef6658b097bcfbcee8f7248bbd5d4df,5cb7c19463750157304fe0488ae19d99d5abdb08da43ac...,https://github.com/pan-unit-42/iocs/blob/maste...

In [9]:
df = df.dropna(subset=['APT-group', 'SHA256'])

In [10]:
df['APT-group'] = (
    df['APT-group']
    .str.upper()
    .str.replace("-", "", regex=False)
    .str.replace(" ", "", regex=False)
)

In [12]:
selected_apts = [
    'GORGONGROUP',
    'APT1',
    'WINNTI',
    'EQUATIONGROUP',
    'APT10',
    'DARKHOTEL',
    'APT29',
    'APT28'
]

df = df[df['APT-group'].isin(selected_apts)]

In [13]:
df['APT-group'].value_counts()

APT-group
GORGONGROUP      1085
APT1              405
EQUATIONGROUP     395
WINNTI            387
APT29             281
DARKHOTEL         273
APT10             244
APT28             215
Name: count, dtype: int64

In [14]:
df[['ID', 'SHA256', 'APT-group', 'Country']].to_csv(
    "../data/processed/labels.csv", index=False
)