In [1]:
import pandas as pd

labels = pd.read_csv("../data/processed/labels.csv")

labels.head()

   ID                                             SHA256 APT-group Country
0   1  b6bc96ffcbdbf22f908a02b8fe2a392c8e5b8420a12093...      APT1   China
1   2  3bff207897f6d8cd8f8e178a565d5efdd7d65c6bc27063...      APT1   China
2   3  df649cef1505653a2fc4361f1e2e34f7148b60c00e1cf6...      APT1   China
3   7  13e40ee7c6874e2f1ed58bc09738a5525f86361f1a8538...      APT1   China
4   9  3eaa53ec7fe5fb610bb9a0dd3d0b93480869b829aac373...      APT1   China

In [2]:
labels['APT-group'].value_counts()

APT-group
GORGONGROUP      1085
APT1              405
EQUATIONGROUP     395
WINNTI            387
APT29             281
DARKHOTEL         273
APT10             244
APT28             215
Name: count, dtype: int64

In [3]:
apt_attack_map = {
    "APT28": ["T1059", "T1027", "T1105", "T1071", "T1055", "T1082"],
    "APT29": ["T1566", "T1204", "T1059", "T1027", "T1071"],
    "APT1": ["T1059", "T1047", "T1086", "T1105"],
    "WINNTI": ["T1059", "T1027", "T1055", "T1071", "T1105"],
    "EQUATIONGROUP": ["T1055", "T1068", "T1027", "T1105"],
    "APT10": ["T1059", "T1086", "T1027", "T1071"],
    "DARKHOTEL": ["T1566", "T1204", "T1059", "T1105"],
    "GORGONGROUP": ["T1059", "T1027", "T1071", "T1105"]
}

In [4]:
import random

def generate_sequence(techniques, min_len=3, max_len=6):
    length = random.randint(min_len, min(max_len, len(techniques)))
    sequence = random.sample(techniques, length)
    return sequence

In [5]:
random.seed(42)

labels["attack_sequence"] = labels["APT-group"].apply(
    lambda apt: generate_sequence(apt_attack_map[apt])
)

labels.head()

,ID,SHA256,APT-group,Country,attack_sequence
0,1,b6bc96ffcbdbf22f908a02b8fe2a392c8e5b8420a12093...,APT1,China,"[T1059, T1086, T1047]"
1,2,3bff207897f6d8cd8f8e178a565d5efdd7d65c6bc27063...,APT1,China,"[T1047, T1059, T1086]"
2,3,df649cef1505653a2fc4361f1e2e34f7148b60c00e1cf6...,APT1,China,"[T1105, T1059, T1086]"
3,7,13e40ee7c6874e2f1ed58bc09738a5525f86361f1a8538...,APT1,China,"[T1047, T1059, T1086]"
4,9,3eaa53ec7fe5fb610bb9a0dd3d0b93480869b829aac373...,APT1,China,"[T1105, T1059, T1047]"

In [6]:
labels.to_csv(
    "../attack_sequences/apt_attack_sequences.csv",
    index=False
)